from tkinter import *
window = Tk()
window.title("Tkinter Window")
window.geometry("300x300")
label = Label(text="window", bg="black", fg="white")
button = Button(text="Click here", bg="white", fg="black") 
entry = Entry(bg="white", fg="black", width=30)
label.pack()
button.pack()
entry.pack()
frame = Frame(master=window, relief=RAISED, borderwidth=4)
frame.pack()
master = Label(master=frame, text="Frame", bg="yellow", fg="black")
master.pack()
textbox = Text(fg="black", bg="white")
textbox.pack()
window.mainloop()